site_name: New Kid in the Cloud
theme:
  name: material
  font:
    code: Roboto Mono
  icon:
    logo: material/cloud
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: deep orange
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: light blue
      accent: amber

      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  markdown_extensions:
    - tables
    - attr_list
    - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  extra:
    social:
      - icon: fontawesome/brands/twitter 
        link: https://twitter.com/coffeecraftcode
      - icon: fontawesome/brands/github
        link: https://github.com/cmgorton  
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/christinagorton/